const { _electron } = require("playwright");
const { spawnSync } = require("node:child_process");
const path = require("node:path"); const os = require("node:os"); const fs = require("node:fs");
const repo = require("path").resolve(__dirname, "..");
(async () => {
  const dataRoot = fs.mkdtempSync(path.join(os.tmpdir(), "tide-lay-"));
  spawnSync("node", [path.join(repo, "scripts/seed-thread.cjs"), dataRoot], { cwd: repo, stdio: "inherit" });
  const app = await _electron.launch({ args: [path.join(repo, "out/main/electron-main.js")], env: { ...process.env, TIDE_APP_DATA_ROOT: dataRoot } });
  const page = await app.firstWindow();
  await page.waitForSelector(".tide-product-shell", { timeout: 20000 });
  await page.waitForTimeout(900);
  await page.locator(".thread-row__main").first().click(); await page.waitForTimeout(900);
  await page.locator('[aria-label="Open Workbench"]').first().click(); await page.waitForTimeout(800);
  await page.locator('[data-launcher-action="open_browser"]').first().click().catch(()=>{}); await page.waitForTimeout(1500);
  await page.locator('[aria-label="Open FileTree"]').first().click(); await page.waitForTimeout(1200);
  const wbW = (await page.locator('[data-column="workbench"]').boundingBox())?.width ?? 0;
  const ftW = (await page.locator('[data-column="file-tree"]').boundingBox())?.width ?? 0;
  const wv = await page.locator('.workbench-browser-webview').boundingBox();
  console.log(`workbench width=${Math.round(wbW)} filetree width=${Math.round(ftW)} bothVisible=${wbW>150 && ftW>150}`);
  console.log(`browser webview height=${Math.round(wv?.height ?? 0)} fillsTall=${(wv?.height ?? 0) > 400}`);
  await page.screenshot({ path: "/tmp/pw-layout.png" });
  await app.close(); console.log("DONE");
})().catch(e=>{console.error("ERR",e);process.exit(1)});
