import type {
  AgentIntegrationCapabilities,
  AgentIntegrationPort,
  AgentIntegrationPreflightInput,
  AgentIntegrationPreflightResult,
  AgentResumePlanInput,
  AgentStartPlanInput,
  ProviderLaunchPlan,
  ProviderSignalSource,
} from "../../../../application/ports/outbound/agent-integration-port.ts";
import type { ThreadScope } from "../../../../application/domains/thread/thread.ts";

// opencode (sst) runs as an ACP agent over stdio (`opencode acp`) — the SAME
// Agent Client Protocol gemini speaks, verified live: initialize →
// session/new → session/prompt with session/update {agent_thought_chunk,
// agent_message_chunk, available_commands_update, usage_update} and
// session/request_permission. So opencode reuses the shared ACP client; this
// adapter only owns preflight + the launch plan. The session id is generated by
// opencode (session/new result), recorded from the protocol — never minted.

export interface OpencodeProviderState {
  authenticated: boolean;
}

export type OpencodeExecutableResolver = (
  command: "opencode",
) => Promise<string | undefined> | string | undefined;

export type OpencodeProviderStateReader = (input: {
  cwd: string;
  executablePath: string;
}) => Promise<OpencodeProviderState> | OpencodeProviderState;

export interface OpencodeTideMcpConfig {
  command: string;
  args: string[];
  env?: Record<string, string>;
}

export interface CreateOpencodeAgentIntegrationInput {
  resolveExecutable: OpencodeExecutableResolver;
  readProviderState: OpencodeProviderStateReader;
  defaultCwd?: string;
  // Tide MCP Tool Surface, attached via the ACP session/new params.mcpServers.
  tideMcp?: OpencodeTideMcpConfig;
}

const opencodeCapabilities: AgentIntegrationCapabilities = {
  supportsHiddenPty: false,
  supportsResume: true,
  supportsTideMcp: true,
  supportsHooks: false,
  supportsReadableHistory: true,
  requiresTerminalKeyProtocol: false,
  // ACP has session/cancel but no mid-turn input injection — follow-up queues.
  supportsTurnSteer: false,
};

const expectedSignalSources: ProviderSignalSource[] = [
  { kind: "provider_history", description: "opencode ACP session updates over stdio." },
  { kind: "tide_mcp", description: "Tide MCP Tool Surface attached via ACP session/new." },
];

export function createOpencodeAgentIntegration(
  input: CreateOpencodeAgentIntegrationInput,
): AgentIntegrationPort {
  return new OpencodeAgentIntegration(input);
}

class OpencodeAgentIntegration implements AgentIntegrationPort {
  private readonly resolveExecutable: OpencodeExecutableResolver;
  private readonly readProviderState: OpencodeProviderStateReader;
  private readonly defaultCwd: string;
  private readonly tideMcp?: OpencodeTideMcpConfig;

  constructor(input: CreateOpencodeAgentIntegrationInput) {
    this.resolveExecutable = input.resolveExecutable;
    this.readProviderState = input.readProviderState;
    this.defaultCwd = input.defaultCwd ?? ".";
    this.tideMcp = input.tideMcp;
  }

  async preflight(
    input: AgentIntegrationPreflightInput,
  ): Promise<AgentIntegrationPreflightResult> {
    const cwd = cwdFromScope(input.scope, this.defaultCwd);
    const executablePath = await this.resolveExecutable("opencode");
    if (executablePath === undefined) {
      return {
        agentId: "opencode",
        ready: false,
        blockers: [
          { kind: "not_installed", scope: "provider", message: "opencode executable was not found." },
        ],
        capabilities: opencodeCapabilities,
      };
    }

    const providerState = await this.readProviderState({ cwd, executablePath });
    if (!providerState.authenticated) {
      return {
        agentId: "opencode",
        ready: false,
        blockers: [
          {
            kind: "not_authenticated",
            scope: "provider",
            message:
              "opencode has no provider credentials yet (run `opencode providers login`).",
            setup: {
              command: executablePath,
              args: ["providers", "login"],
              cwd,
              expectedCompletion: "retry_preflight",
            },
          },
        ],
        capabilities: opencodeCapabilities,
      };
    }

    return {
      agentId: "opencode",
      ready: true,
      blockers: [],
      capabilities: opencodeCapabilities,
      launchPlan: this.opencodeLaunchPlan({ executablePath, cwd }),
    };
  }

  async buildStartPlan(input: AgentStartPlanInput): Promise<ProviderLaunchPlan> {
    const executablePath = (await this.resolveExecutable("opencode")) ?? "opencode";
    const cwd = cwdFromScope(input.scope, this.defaultCwd);
    return this.opencodeLaunchPlan({ executablePath, cwd });
  }

  async buildResumePlan(input: AgentResumePlanInput): Promise<ProviderLaunchPlan> {
    const executablePath = (await this.resolveExecutable("opencode")) ?? "opencode";
    const cwd = cwdFromScope(input.scope, this.defaultCwd);
    return this.opencodeLaunchPlan({ executablePath, cwd, resumeRef: input.providerSessionRef.value });
  }

  private opencodeLaunchPlan(input: {
    executablePath: string;
    cwd: string;
    resumeRef?: string;
  }): ProviderLaunchPlan {
    // STRUCTURED TRANSPORT: ACP over stdio (`opencode acp`). The shared ACP
    // client drives initialize → session/new (resume via session/load) →
    // session/prompt; the session id comes from the protocol response.
    return {
      command: input.executablePath,
      args: ["acp"],
      env: {},
      cwd: input.cwd,
      transport: "acp",
      protocolParams: {
        cwd: input.cwd,
        ...(this.tideMcp !== undefined
          ? {
              mcpServers: [
                {
                  name: "tide",
                  command: this.tideMcp.command,
                  args: this.tideMcp.args,
                  env: Object.entries(this.tideMcp.env ?? {}).map(([name, value]) => ({ name, value })),
                },
              ],
            }
          : {}),
      },
      expectedSignalSources: expectedSignalSources.map((source) => ({ ...source })),
    };
  }
}

function cwdFromScope(scope: ThreadScope | undefined, fallback: string): string {
  if (scope === undefined) {
    return fallback;
  }
  return scope.kind === "project" ? scope.cwd : scope.scratchCwd;
}
