import type {
  AgentIntegrationCapabilities,
  AgentIntegrationPort,
  AgentIntegrationPreflightInput,
  AgentIntegrationPreflightResult,
  AgentResumePlanInput,
  AgentStartPlanInput,
  ProviderLaunchPlan,
  SessionConfigUpdateInput,
  SessionConfigUpdatePlan,
} from "../../../../application/ports/outbound/agent-integration-port.ts";
import type { ThreadScope } from "../../../../application/domains/thread/thread.ts";
import { npmInstallSetupAction } from "../shared/provider-cli-commands.ts";

// opencode (sst) runs as an ACP agent over stdio (`opencode acp`) — the SAME
// Agent Client Protocol gemini speaks, verified live: initialize →
// session/new → session/prompt with session/update {agent_thought_chunk,
// agent_message_chunk, available_commands_update, usage_update} and
// session/request_permission. So opencode reuses the shared ACP client; this
// adapter only owns preflight + the launch plan. The session id is generated by
// opencode (session/new result), recorded from the protocol — never minted.

export interface OpencodeProviderState {
  authenticated: boolean;
}

export type OpencodeExecutableResolver = (
  command: "opencode" | "npm",
) => Promise<string | undefined> | string | undefined;

export type OpencodeProviderStateReader = (input: {
  cwd: string;
  executablePath: string;
}) => Promise<OpencodeProviderState> | OpencodeProviderState;

export interface OpencodeTideMcpConfig {
  command: string;
  args: string[];
  env?: Record<string, string>;
}

export interface CreateOpencodeAgentIntegrationInput {
  resolveExecutable: OpencodeExecutableResolver;
  readProviderState: OpencodeProviderStateReader;
  defaultCwd?: string;
  // Tide MCP Tool Surface, attached via the ACP session/new params.mcpServers.
  tideMcp?: OpencodeTideMcpConfig;
}

const opencodeCapabilities: AgentIntegrationCapabilities = {
  supportsResume: true,
  supportsTideMcp: true,
  supportsHooks: false,
  supportsReadableHistory: true,
  // ACP has session/cancel but no mid-turn input injection — follow-up queues.
  supportsTurnSteer: false,
};

export function createOpencodeAgentIntegration(
  input: CreateOpencodeAgentIntegrationInput,
): AgentIntegrationPort {
  return new OpencodeAgentIntegration(input);
}

class OpencodeAgentIntegration implements AgentIntegrationPort {
  private readonly resolveExecutable: OpencodeExecutableResolver;
  private readonly readProviderState: OpencodeProviderStateReader;
  private readonly defaultCwd: string;
  private readonly tideMcp?: OpencodeTideMcpConfig;

  constructor(input: CreateOpencodeAgentIntegrationInput) {
    this.resolveExecutable = input.resolveExecutable;
    this.readProviderState = input.readProviderState;
    this.defaultCwd = input.defaultCwd ?? ".";
    this.tideMcp = input.tideMcp;
  }

  async preflight(
    input: AgentIntegrationPreflightInput,
  ): Promise<AgentIntegrationPreflightResult> {
    const cwd = cwdFromScope(input.scope, this.defaultCwd);
    const executablePath = await this.resolveExecutable("opencode");
    if (executablePath === undefined) {
      const npmPath = (await this.resolveExecutable("npm")) ?? "npm";
      return {
        agentId: "opencode",
        ready: false,
        blockers: [
          {
            kind: "not_installed",
            scope: "provider",
            message: "opencode executable was not found.",
            setup: npmInstallSetupAction({ npmPath, agentId: "opencode", cwd }),
          },
        ],
        capabilities: opencodeCapabilities,
      };
    }

    const providerState = await this.readProviderState({ cwd, executablePath });
    if (!providerState.authenticated) {
      return {
        agentId: "opencode",
        ready: false,
        blockers: [
          {
            kind: "not_authenticated",
            scope: "provider",
            message:
              "opencode has no vendor signed in yet — run `opencode auth login` to add one " +
              "(OpenAI, Anthropic, Qwen, Kimi, …).",
            // The Provider Setup Surface drives opencode's own `auth login` flow in a
            // terminal (vendor pick → OAuth or API key); Tide does not reimplement it.
            // This is also the "+ add vendor" path for a multi-vendor router.
            setup: {
              command: executablePath,
              args: ["auth", "login"],
              cwd,
              expectedCompletion: "retry_preflight",
            },
          },
        ],
        capabilities: opencodeCapabilities,
      };
    }

    return {
      agentId: "opencode",
      ready: true,
      blockers: [],
      capabilities: opencodeCapabilities,
      launchPlan: this.opencodeLaunchPlan({ executablePath, cwd }),
    };
  }

  async buildStartPlan(input: AgentStartPlanInput): Promise<ProviderLaunchPlan> {
    const executablePath = (await this.resolveExecutable("opencode")) ?? "opencode";
    const cwd = cwdFromScope(input.scope, this.defaultCwd);
    return this.opencodeLaunchPlan({ executablePath, cwd, launchOptions: input.launchOptions });
  }

  async buildResumePlan(input: AgentResumePlanInput): Promise<ProviderLaunchPlan> {
    const executablePath = (await this.resolveExecutable("opencode")) ?? "opencode";
    const cwd = cwdFromScope(input.scope, this.defaultCwd);
    return this.opencodeLaunchPlan({
      executablePath,
      cwd,
      launchOptions: input.launchOptions,
      resumeRef: input.providerSessionRef.value,
    });
  }

  // opencode model / effort / permission all apply LIVE over ACP via
  // `session/set_config_option` (configId model | effort | mode) — verified live, no
  // restart for any of them. Each changed key maps to a config option the ACP client
  // delivers; the session reports refreshed configOptions in the response.
  buildSessionConfigUpdate(input: SessionConfigUpdateInput): SessionConfigUpdatePlan {
    const configOptions = opencodeConfigOptions(input.launchOptions, input.changedKeys);
    return { kind: "live", protocolParams: { configOptions } };
  }

  private opencodeLaunchPlan(input: {
    executablePath: string;
    cwd: string;
    launchOptions?: Record<string, unknown>;
    resumeRef?: string;
  }): ProviderLaunchPlan {
    // STRUCTURED TRANSPORT: ACP over stdio (`opencode acp`). The shared ACP
    // client drives initialize → session/new (resume via session/load) →
    // session/prompt; the session id comes from the protocol response.
    return {
      command: input.executablePath,
      args: ["acp"],
      env: {},
      cwd: input.cwd,
      transport: "acp",
      protocolParams: {
        cwd: input.cwd,
        // The chosen model / effort / mode, applied by the ACP client right after
        // session/new (before the first prompt) via session/set_config_option.
        configOptions: opencodeConfigOptions(input.launchOptions, ["model", "reasoning", "permission"]),
        ...(this.tideMcp !== undefined
          ? {
              mcpServers: [
                {
                  name: "tide",
                  command: this.tideMcp.command,
                  args: this.tideMcp.args,
                  env: Object.entries(this.tideMcp.env ?? {}).map(([name, value]) => ({ name, value })),
                },
              ],
            }
          : {}),
      },
    };
  }
}

function cwdFromScope(scope: ThreadScope | undefined, fallback: string): string {
  if (scope === undefined) {
    return fallback;
  }
  return scope.kind === "project" ? scope.cwd : scope.scratchCwd;
}

function stringValue(value: unknown): string | undefined {
  return typeof value === "string" && value.length > 0 ? value : undefined;
}

// Map Tide Launch Options to opencode ACP `set_config_option` entries for the given
// changed keys: model → configId "model" (the sentinel "opencode default" sets
// nothing — honor opencode's own default), reasoning → "effort", permission → "mode"
// (opencode exposes only build | plan; everything but "plan" is "build").
export function opencodeConfigOptions(
  launchOptions: Record<string, unknown> | undefined,
  changedKeys: ReadonlyArray<string>,
): Array<{ configId: string; value: string }> {
  const options: Array<{ configId: string; value: string }> = [];
  for (const key of changedKeys) {
    if (key === "model") {
      const model = stringValue(launchOptions?.model);
      if (model !== undefined && model !== "opencode default") {
        options.push({ configId: "model", value: model });
      }
      continue;
    }
    if (key === "reasoning") {
      const effort = stringValue(launchOptions?.reasoning);
      if (effort !== undefined) {
        options.push({ configId: "effort", value: effort });
      }
      continue;
    }
    if (key === "permission") {
      const permission = stringValue(launchOptions?.permission);
      options.push({ configId: "mode", value: permission === "plan" ? "plan" : "build" });
    }
  }
  return options;
}
